const arr = [
    {
        "_id": "6591466835ed2a3169ce3823",
        "Gmina": "Bochnia",
        "Powiat": "bocheński",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "76,52",
        "Procent głosów nieważnych": "1,15",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,01",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "23,28",
        "KOMITET WYBORCZY NOWA LEWICA": "4,58",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "37,94",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "7,55",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "23,33",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,31"
    },
    {
        "_id": "6591466835ed2a3169ce3824",
        "Gmina": "Bochnia",
        "Powiat": "bocheński",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "73,97",
        "Procent głosów nieważnych": "1,80",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,34",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "19,10",
        "KOMITET WYBORCZY NOWA LEWICA": "3,33",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "52,99",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "8,34",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "12,53",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,39"
    },
    {
        "_id": "6591466835ed2a3169ce3825",
        "Gmina": "Drwinia",
        "Powiat": "bocheński",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "73,08",
        "Procent głosów nieważnych": "1,17",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,23",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "17,44",
        "KOMITET WYBORCZY NOWA LEWICA": "3,03",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "60,14",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "8,75",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "7,73",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "1,66"
    },
    {
        "_id": "6591466835ed2a3169ce3826",
        "Gmina": "Lipnica Murowana",
        "Powiat": "bocheński",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "72,89",
        "Procent głosów nieważnych": "2,48",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,31",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "14,05",
        "KOMITET WYBORCZY NOWA LEWICA": "1,88",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "63,06",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "7,07",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "10,90",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "1,74"
    },
    {
        "_id": "6591466835ed2a3169ce3827",
        "Gmina": "Łapanów",
        "Powiat": "bocheński",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "75,22",
        "Procent głosów nieważnych": "1,81",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,34",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "19,43",
        "KOMITET WYBORCZY NOWA LEWICA": "2,99",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "54,64",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "9,04",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "10,26",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,30"
    },
    {
        "_id": "6591466835ed2a3169ce3828",
        "Gmina": "Nowy Wiśnicz",
        "Powiat": "bocheński",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "78,00",
        "Procent głosów nieważnych": "1,63",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,16",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "17,04",
        "KOMITET WYBORCZY NOWA LEWICA": "2,99",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "56,05",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "7,67",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "12,69",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,41"
    },
    {
        "_id": "6591466835ed2a3169ce3829",
        "Gmina": "Rzezawa",
        "Powiat": "bocheński",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "72,61",
        "Procent głosów nieważnych": "1,42",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,36",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "16,09",
        "KOMITET WYBORCZY NOWA LEWICA": "3,65",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "55,78",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "9,43",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "11,39",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,29"
    },
    {
        "_id": "6591466835ed2a3169ce382a",
        "Gmina": "Trzciana",
        "Powiat": "bocheński",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "79,17",
        "Procent głosów nieważnych": "1,69",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "0,97",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "16,56",
        "KOMITET WYBORCZY NOWA LEWICA": "2,05",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "62,65",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "7,36",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "7,51",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,90"
    },
    {
        "_id": "6591466835ed2a3169ce382b",
        "Gmina": "Żegocina",
        "Powiat": "bocheński",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "79,60",
        "Procent głosów nieważnych": "1,28",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "0,86",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "12,04",
        "KOMITET WYBORCZY NOWA LEWICA": "1,85",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "68,46",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "7,81",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "6,14",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,84"
    },
    {
        "_id": "6591466835ed2a3169ce3849",
        "Gmina": "Czernichów",
        "Powiat": "krakowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 13,
        "Frekwencja": "73,89",
        "Procent głosów nieważnych": "1,73",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,87",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "16,10",
        "KOMITET WYBORCZY NOWA LEWICA": "6,21",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "44,54",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "9,34",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "20,45",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "1,50"
    },
    {
        "_id": "6591466835ed2a3169ce384a",
        "Gmina": "Igołomia-Wawrzeńczyce",
        "Powiat": "krakowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 13,
        "Frekwencja": "69,98",
        "Procent głosów nieważnych": "2,02",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,05",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "15,10",
        "KOMITET WYBORCZY NOWA LEWICA": "4,58",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "53,39",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "10,38",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "14,46",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "1,03"
    },
    {
        "_id": "6591466835ed2a3169ce384b",
        "Gmina": "Iwanowice",
        "Powiat": "krakowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 13,
        "Frekwencja": "76,23",
        "Procent głosów nieważnych": "2,15",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,89",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "15,50",
        "KOMITET WYBORCZY NOWA LEWICA": "4,47",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "49,57",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "9,00",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "17,94",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "1,63"
    },
    {
        "_id": "6591466835ed2a3169ce384c",
        "Gmina": "Jerzmanowice-Przeginia",
        "Powiat": "krakowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 13,
        "Frekwencja": "76,04",
        "Procent głosów nieważnych": "2,35",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,30",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "13,22",
        "KOMITET WYBORCZY NOWA LEWICA": "6,05",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "53,19",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "9,06",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "15,83",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "1,35"
    },
    {
        "_id": "6591466835ed2a3169ce384d",
        "Gmina": "Kocmyrzów-Luborzyca",
        "Powiat": "krakowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 13,
        "Frekwencja": "77,07",
        "Procent głosów nieważnych": "1,77",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,66",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "18,51",
        "KOMITET WYBORCZY NOWA LEWICA": "6,34",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "40,89",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "8,27",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "22,30",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,03"
    },
    {
        "_id": "6591466835ed2a3169ce384e",
        "Gmina": "Krzeszowice",
        "Powiat": "krakowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 13,
        "Frekwencja": "75,87",
        "Procent głosów nieważnych": "1,72",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,63",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "13,63",
        "KOMITET WYBORCZY NOWA LEWICA": "6,89",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "38,96",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "7,79",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "29,21",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "1,90"
    },
    {
        "_id": "6591466835ed2a3169ce384f",
        "Gmina": "Liszki",
        "Powiat": "krakowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 13,
        "Frekwencja": "77,35",
        "Procent głosów nieważnych": "1,62",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,24",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "15,43",
        "KOMITET WYBORCZY NOWA LEWICA": "5,78",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "45,82",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "8,95",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "20,94",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "1,84"
    },
    {
        "_id": "6591466835ed2a3169ce3850",
        "Gmina": "Michałowice",
        "Powiat": "krakowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 13,
        "Frekwencja": "82,19",
        "Procent głosów nieważnych": "1,42",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,67",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "18,96",
        "KOMITET WYBORCZY NOWA LEWICA": "6,52",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "33,22",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "8,21",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "29,37",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,03"
    },
    {
        "_id": "6591466835ed2a3169ce3851",
        "Gmina": "Mogilany",
        "Powiat": "krakowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 13,
        "Frekwencja": "81,50",
        "Procent głosów nieważnych": "1,68",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,39",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "16,13",
        "KOMITET WYBORCZY NOWA LEWICA": "6,79",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "35,59",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "8,76",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "29,11",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,23"
    },
    {
        "_id": "6591466835ed2a3169ce3852",
        "Gmina": "Skała",
        "Powiat": "krakowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 13,
        "Frekwencja": "77,61",
        "Procent głosów nieważnych": "1,98",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,56",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "14,72",
        "KOMITET WYBORCZY NOWA LEWICA": "6,73",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "47,73",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "8,66",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "19,42",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "1,18"
    },
    {
        "_id": "6591466835ed2a3169ce3853",
        "Gmina": "Skawina",
        "Powiat": "krakowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 13,
        "Frekwencja": "76,55",
        "Procent głosów nieważnych": "1,47",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,59",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "17,38",
        "KOMITET WYBORCZY NOWA LEWICA": "6,53",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "38,47",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "8,91",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "25,38",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "1,74"
    },
    {
        "_id": "6591466835ed2a3169ce3854",
        "Gmina": "Słomniki",
        "Powiat": "krakowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 13,
        "Frekwencja": "73,10",
        "Procent głosów nieważnych": "1,90",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,22",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "16,41",
        "KOMITET WYBORCZY NOWA LEWICA": "4,80",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "49,28",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "9,17",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "16,25",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,87"
    },
    {
        "_id": "6591466835ed2a3169ce3855",
        "Gmina": "Sułoszowa",
        "Powiat": "krakowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 13,
        "Frekwencja": "78,44",
        "Procent głosów nieważnych": "2,25",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,13",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "19,28",
        "KOMITET WYBORCZY NOWA LEWICA": "2,91",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "58,48",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "7,10",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "8,84",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,27"
    },
    {
        "_id": "6591466835ed2a3169ce3856",
        "Gmina": "Świątniki Górne",
        "Powiat": "krakowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 13,
        "Frekwencja": "77,51",
        "Procent głosów nieważnych": "1,29",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,34",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "17,34",
        "KOMITET WYBORCZY NOWA LEWICA": "5,58",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "40,51",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "8,10",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "24,79",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,33"
    },
    {
        "_id": "6591466835ed2a3169ce3857",
        "Gmina": "Wielka Wieś",
        "Powiat": "krakowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 13,
        "Frekwencja": "84,33",
        "Procent głosów nieważnych": "1,18",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,54",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "18,20",
        "KOMITET WYBORCZY NOWA LEWICA": "7,69",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "31,82",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "8,93",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "30,31",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "1,51"
    },
    {
        "_id": "6591466835ed2a3169ce3858",
        "Gmina": "Zabierzów",
        "Powiat": "krakowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 13,
        "Frekwencja": "82,92",
        "Procent głosów nieważnych": "1,37",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,32",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "15,66",
        "KOMITET WYBORCZY NOWA LEWICA": "7,51",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "32,25",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "8,11",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "33,51",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "1,63"
    },
    {
        "_id": "6591466835ed2a3169ce3859",
        "Gmina": "Zielonki",
        "Powiat": "krakowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 13,
        "Frekwencja": "84,49",
        "Procent głosów nieważnych": "1,18",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,54",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "18,75",
        "KOMITET WYBORCZY NOWA LEWICA": "8,41",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "27,92",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "7,98",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "33,92",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "1,48"
    },
    {
        "_id": "6591466e35ed2a3169ce38b2",
        "Gmina": "Ciężkowice",
        "Powiat": "tarnowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "67,76",
        "Procent głosów nieważnych": "2,21",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,72",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "17,91",
        "KOMITET WYBORCZY NOWA LEWICA": "2,81",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "58,41",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "6,70",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "10,59",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "1,86"
    },
    {
        "_id": "6591466e35ed2a3169ce38b3",
        "Gmina": "Gromnik",
        "Powiat": "tarnowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "67,07",
        "Procent głosów nieważnych": "1,87",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,42",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "11,74",
        "KOMITET WYBORCZY NOWA LEWICA": "2,57",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "66,32",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "7,47",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "7,27",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "3,21"
    },
    {
        "_id": "6591466e35ed2a3169ce38b4",
        "Gmina": "Lisia Góra",
        "Powiat": "tarnowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "71,13",
        "Procent głosów nieważnych": "1,32",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,62",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "15,84",
        "KOMITET WYBORCZY NOWA LEWICA": "2,77",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "56,11",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "8,74",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "11,93",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,99"
    },
    {
        "_id": "6591466e35ed2a3169ce38b5",
        "Gmina": "Pleśna",
        "Powiat": "tarnowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "69,89",
        "Procent głosów nieważnych": "1,61",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,41",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "16,27",
        "KOMITET WYBORCZY NOWA LEWICA": "3,06",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "56,30",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "7,43",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "12,78",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,75"
    },
    {
        "_id": "6591466e35ed2a3169ce38b6",
        "Gmina": "Radłów",
        "Powiat": "tarnowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "67,18",
        "Procent głosów nieważnych": "2,08",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,66",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "16,63",
        "KOMITET WYBORCZY NOWA LEWICA": "3,68",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "55,84",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "7,98",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "11,97",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,24"
    },
    {
        "_id": "6591466e35ed2a3169ce38b7",
        "Gmina": "Ryglice",
        "Powiat": "tarnowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "68,06",
        "Procent głosów nieważnych": "2,29",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,85",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "12,91",
        "KOMITET WYBORCZY NOWA LEWICA": "2,94",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "59,85",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "9,31",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "10,27",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,86"
    },
    {
        "_id": "6591466e35ed2a3169ce38b8",
        "Gmina": "Rzepiennik Strzyżewski",
        "Powiat": "tarnowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "71,81",
        "Procent głosów nieważnych": "1,52",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,93",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "11,53",
        "KOMITET WYBORCZY NOWA LEWICA": "1,99",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "66,37",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "9,30",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "5,77",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "3,12"
    },
    {
        "_id": "6591466e35ed2a3169ce38b9",
        "Gmina": "Skrzyszów",
        "Powiat": "tarnowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "71,37",
        "Procent głosów nieważnych": "1,28",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,63",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "15,27",
        "KOMITET WYBORCZY NOWA LEWICA": "3,25",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "55,11",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "8,57",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "14,00",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,16"
    },
    {
        "_id": "6591466e35ed2a3169ce38ba",
        "Gmina": "Tarnów",
        "Powiat": "tarnowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "74,00",
        "Procent głosów nieważnych": "1,15",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,34",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "19,54",
        "KOMITET WYBORCZY NOWA LEWICA": "4,04",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "47,81",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "7,67",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "17,28",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,31"
    },
    {
        "_id": "6591466e35ed2a3169ce38bb",
        "Gmina": "Tuchów",
        "Powiat": "tarnowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "69,43",
        "Procent głosów nieważnych": "1,72",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,63",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "14,71",
        "KOMITET WYBORCZY NOWA LEWICA": "3,14",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "58,33",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "7,85",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "10,86",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "3,48"
    },
    {
        "_id": "6591466e35ed2a3169ce38bc",
        "Gmina": "Wierzchosławice",
        "Powiat": "tarnowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "72,92",
        "Procent głosów nieważnych": "2,26",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,42",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "18,66",
        "KOMITET WYBORCZY NOWA LEWICA": "3,97",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "50,11",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "8,53",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "14,85",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,46"
    },
    {
        "_id": "6591466e35ed2a3169ce38bd",
        "Gmina": "Wietrzychowice",
        "Powiat": "tarnowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "56,77",
        "Procent głosów nieważnych": "2,31",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "3,25",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "22,64",
        "KOMITET WYBORCZY NOWA LEWICA": "2,19",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "55,08",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "6,97",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "8,10",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "1,77"
    },
    {
        "_id": "6591466e35ed2a3169ce38be",
        "Gmina": "Wojnicz",
        "Powiat": "tarnowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "71,59",
        "Procent głosów nieważnych": "1,75",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,68",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "15,95",
        "KOMITET WYBORCZY NOWA LEWICA": "3,20",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "54,59",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "9,07",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "12,83",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,68"
    },
    {
        "_id": "6591466e35ed2a3169ce38bf",
        "Gmina": "Zakliczyn",
        "Powiat": "tarnowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "69,68",
        "Procent głosów nieważnych": "2,03",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,48",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "14,39",
        "KOMITET WYBORCZY NOWA LEWICA": "2,92",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "59,01",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "9,10",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "10,23",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,86"
    },
    {
        "_id": "6591466e35ed2a3169ce38c0",
        "Gmina": "Żabno",
        "Powiat": "tarnowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "66,12",
        "Procent głosów nieważnych": "1,63",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,69",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "20,20",
        "KOMITET WYBORCZY NOWA LEWICA": "3,33",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "52,96",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "7,29",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "12,52",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,00"
    },
    {
        "_id": "6591466e35ed2a3169ce38c1",
        "Gmina": "Szerzyny",
        "Powiat": "tarnowski",
        "Województwo": "małopolskie",
        "Nr okręgu": 15,
        "Frekwencja": "68,51",
        "Procent głosów nieważnych": "2,32",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,85",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "12,41",
        "KOMITET WYBORCZY NOWA LEWICA": "2,20",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "67,10",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "8,23",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "5,70",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,50"
    },
    {
        "_id": "6591466e35ed2a3169ce3bb5",
        "Gmina": "Lębork",
        "Powiat": "lęborski",
        "Województwo": "pomorskie",
        "Nr okręgu": 26,
        "Frekwencja": "72,65",
        "Procent głosów nieważnych": "1,47",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,37",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "12,21",
        "KOMITET WYBORCZY NOWA LEWICA": "8,93",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "27,00",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "7,00",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "41,97",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "1,52"
    },
    {
        "_id": "6591466e35ed2a3169ce3bb6",
        "Gmina": "Łeba",
        "Powiat": "lęborski",
        "Województwo": "pomorskie",
        "Nr okręgu": 26,
        "Frekwencja": "76,60",
        "Procent głosów nieważnych": "1,08",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,35",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "11,52",
        "KOMITET WYBORCZY NOWA LEWICA": "8,29",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "28,10",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "5,72",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "43,06",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "1,96"
    },
    {
        "_id": "6591466e35ed2a3169ce3bb7",
        "Gmina": "Cewice",
        "Powiat": "lęborski",
        "Województwo": "pomorskie",
        "Nr okręgu": 26,
        "Frekwencja": "71,60",
        "Procent głosów nieważnych": "2,67",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,73",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "15,27",
        "KOMITET WYBORCZY NOWA LEWICA": "6,29",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "36,94",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "8,28",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "28,72",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,77"
    },
    {
        "_id": "6591466e35ed2a3169ce3bb8",
        "Gmina": "Nowa Wieś Lęborska",
        "Powiat": "lęborski",
        "Województwo": "pomorskie",
        "Nr okręgu": 26,
        "Frekwencja": "69,75",
        "Procent głosów nieważnych": "1,91",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,84",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "14,26",
        "KOMITET WYBORCZY NOWA LEWICA": "7,64",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "31,96",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "7,99",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "34,39",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "1,91"
    },
    {
        "_id": "6591466e35ed2a3169ce3bb9",
        "Gmina": "Wicko",
        "Powiat": "lęborski",
        "Województwo": "pomorskie",
        "Nr okręgu": 26,
        "Frekwencja": "66,35",
        "Procent głosów nieważnych": "2,08",
        "KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY": "1,91",
        "KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE": "14,41",
        "KOMITET WYBORCZY NOWA LEWICA": "9,44",
        "KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ": "32,14",
        "KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ": "8,29",
        "KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO N IPL ZIELONI": "31,68",
        "KOMITET WYBORCZY POLSKA JEST JEDNA": "2,13"
    }
]

console.log(arr.length)