enum Parties {
  NUM1 = 'KOMITET WYBORCZY BEZPARTYJNI SAMORZĄDOWCY',
  NUM2 = 'KOALICYJNY KOMITET WYBORCZY TRZECIA DROGA POLSKA 2050 SZYMONA HOŁOWNI - POLSKIE STRONNICTWO LUDOWE',
  NUM3 = 'KOMITET WYBORCZY NOWA LEWICA',
  NUM4 = 'KOMITET WYBORCZY PRAWO I SPRAWIEDLIWOŚĆ',
  NUM5 = 'KOMITET WYBORCZY KONFEDERACJA WOLNOŚĆ I NIEPODLEGŁOŚĆ',
  NUM6 = 'KOALICYJNY KOMITET WYBORCZY KOALICJA OBYWATELSKA PO .N IPL ZIELONI',
  NUM7 = 'KOMITET WYBORCZY POLSKA JEST JEDNA',
  NUM8 = 'KOMITET WYBORCZY WYBORCÓW RUCHU DOBROBYTU I POKOJU',
  NUM9 = 'KOMITET WYBORCZY NORMALNY KRAJ',
  NUM10 = 'KOMITET WYBORCZY ANTYPARTIA',
  NUM11 = 'KOMITET WYBORCZY RUCH NAPRAWY POLSKI',
  NUM12 = 'KOMITET WYBORCZY WYBORCÓW MNIEJSZOŚĆ NIEMIECKA',
}
